trigger:
- master
jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: Powershell@2
    displayName: Build
    inputs:
      targetType: inline
      script: |
        cd $(Build.SourcesDirectory)
        $env:ADOBUILDID = "$(Build.BuildId)"
        py write-deploy-parameters.py
        $env:GOOGLECREDS | Out-File google-creds.json
        dotnet publish -c Release
        "Build ID: $(Build.BuildId)" | Out-File "$(Build.SourcesDirectory)/bin/Release/netcoreapp2.1/publish/source.txt"
  - task: ArchiveFiles@2
    displayName: Zip package
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/bin/Release/netcoreapp2.1/publish/' 
      includeRootFolder: false
      archiveFile: '$(Build.SourcesDirectory)/package.zip'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.SourcesDirectory)/package.zip' 
      artifactName: 'drop' 
  - task: AzureResourceGroupDeployment@2
    displayName: GET OUT THE CREDIT CARD, BABY!
    inputs:
      azureSubscription: '$(AzureServiceConnectionName)'
      action: 'Create Or Update Resource Group'
      resourceGroupName: '$(AzureResourceGroupName)'
      location: 'West US'
      templateLocation: 'Linked artifact'
      csmFile: 'azuredeploy.json'
      deploymentMode: 'Incremental'
      csmParametersFile: 'azuredeploy-parameters.json'
  - task: AzureFunctionApp@1
    displayName: Azure Function App Deploy
    inputs:
      azureSubscription: $(AzureServiceConnectionName)
      resourceGroupName: $(AzureResourceGroupName)
      appName: $(AppName)
      package: $(Build.SourcesDirectory)/package.zip
  