trigger:
- master
jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - task:
      targetType: inline
      script: |
        cd $(Build.SourcesDirectory)
        py write-deploy-parameters.py
        dotnet publish -c Release
        echo $env:GOOGLECREDS
        $env:GOOGLECREDS | Out-File bin/Release/netcoreapp2.1/publish/google-creds.json
        echo "Here!"
        Compress-Archive -Path bin/Release/netcoreapp2.1/publish -DestinationPath package.zip -Force
  - task: AzureResourceGroupDeployment@2
    displayName: GET OUT THE CREDIT CARD, BABY!
    inputs:
      azureSubscription: '$(AzureServiceConnectionName)'
      action: 'Create Or Update Resource Group'
      resourceGroupName: '$(AzureResourceGroupName)'
      location: 'West US'
      templateLocation: 'Linked artifact'
      csmFile: 'azuredeploy.json'
      deploymentMode: 'Incremental'
      csmParametersFile: 'azuredeploy-parameters.json'
  - task: AzureFunctionApp@1
    displayName: Azure Function App Deploy
    inputs:
      azureSubscription: $(AzureServiceConnectionName)
      appName: $(AppName)
      package: $(Build.SourcesDirectory)/package.zip
  